(function ensightenInit(){var ensightenOptions = {client: "rbc", clientId: 661, publishPath: "olb", isPublic:0, serverComponentLocation: "nexus.ensighten.com/rbc/olb/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/rbc/olb/code/", ns: 'Bootstrapper', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "false", enablePagePerfBeacon : "false", registryNs : "ensBootstraps", generatedOn : "Fri Aug 25 10:51:54 GMT 2017", beaconSamplingSeedValue: 11};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(f){function l(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function m(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function n(){for(var a=b.dataDefinitionIds.length,d=!0,e=0;e<a;e++){var c=b.dataDefinitions[b.dataDefinitionIds[e]];if(!c||
null==c.endRegistration){d=!1;break}}d&&b.callOnDataDefintionComplete()}var c={},b={};b.ensightenOptions=ensightenOptions;b.scDataObj={};c.version="1.26.0";c.nexus=f.nexus||"nexus.ensighten.com";c.rand=-1;c.currSec=(new Date).getSeconds();c.options={interval:f.interval||100,erLoc:f.errorLocation||c.nexus+"/error/e.gif",scLoc:f.serverComponentLocation||c.nexus+"/"+f.client+"/serverComponent.php",sjPath:f.staticJavascriptPath||c.nexus+"/"+f.client+"/code/",alLoc:f.alertLocation||c.nexus+"/alerts/a.gif",
publishPath:f.publishPath,isPublic:f.isPublic,client:f.client,clientId:f.clientId,enableTagAuditBeacon:f.enableTagAuditBeacon,scUseCacheBuster:f.scUseCacheBuster,beaconSamplingSeedValue:f.beaconSamplingSeedValue||-1};c.ruleList=[];c.allDeploymentIds=[];c.runDeploymentIds=[];c.runRuleIds=[];c.exceptionList=[];c.ensightenVariables={};c.test=function(a){if(!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var d=0;d<a.dependencies.length;d++)if(!1===a.dependencies[d]())return;
a.execute()}};l.prototype=Error();l.prototype||(l.prototype={});l.prototype.constructor=l;c.DependencyNotAvailableException=l;m.prototype=Error();m.prototype||(m.prototype={});m.prototype.constructor=m;c.BeaconException=m;c.checkForInvalidDependencies=function(a,d,e,h){for(a=0;a<e.length;a++)if("DEPENDENCYNEVERAVAILABLE"===e[a])return b.currentRuleId=this.id,b.currentDeploymentId=this.deploymentId,b.reportException(new c.DependencyNotAvailableException(h[a])),d&&-1!==d&&c.allDeploymentIds.push(d),
!0;return!1};b.currentRuleId=-1;b.currentDeploymentId=-1;b.reportedErrors=[];b.reportedAlerts=[];b.AF=[];b._serverTime="";b._clientIP="";b.sampleBeacon=function(){var a=!1;try{var d=(c.currSec||0)%20,b=c.options.beaconSamplingSeedValue;-1===b?a=!0:0!==d&&0===b%d&&(a=!0)}catch(h){}return a};b.getServerComponent=function(a){b.callOnGetServerComponent();b.insertScript(window.location.protocol+"//"+c.options.scLoc,!1,a||!0,c.options.scUseCacheBuster)};b.setVariable=function(a,b){c.ensightenVariables[a]=
b};b.getVariable=function(a){return a in c.ensightenVariables?c.ensightenVariables[a]:null};b.testAll=function(){for(var a=0;a<c.ruleList.length;a++)c.test(c.ruleList[a])};b.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};b.reportException=function(a){a.timestamp=(new Date).getTime();c.exceptionList.push(a);a=window.location.protocol+"//"+c.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||
a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(c.options.clientId||-1)+"&client="+encodeURIComponent(c.options.client||"")+"&publishPath="+encodeURIComponent(c.options.publishPath||"")+"&rid="+encodeURIComponent(b.currentRuleId||-1)+"&did="+encodeURIComponent(b.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=b.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};b.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);
b.currentRuleId=this.id;b.currentDeploymentId=this.deploymentId;try{this.code()}catch(d){window[ensightenOptions.ns].reportException(d)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&(c.runDeploymentIds.push(this.deploymentId),c.runRuleIds.push(this.id)),b.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.executionData={hasRun:!1,runTime:[]}};b.registerRule=function(a){if(b.getRule(a.id)&&-1!==a.id)return!1;c.ruleList.push(a);
-1!==a.deploymentId&&c.allDeploymentIds.push(a.deploymentId);b.testAll();return!0};b.getRule=function(a){for(var b=0;b<c.ruleList.length;b++)if(c.ruleList[b].id===a)return c.ruleList[b];return!1};b.getRuleList=function(){return c.ruleList};b.clearRuleList=function(){c.ruleList=[]};b.getAllDeploymentIds=function(){return c.allDeploymentIds};b.getRunRuleIds=function(){return c.runRuleIds};b.getRunDeploymentIds=function(){return c.runDeploymentIds};b.hasRuleRun=function(a){return(a=b.getRule(a))?a.executionData.hasRun:
!1};c.toTwoChar=function(a){return(2===a.toString().length?"":"0")+a};b.Alert=function(a){var b=new Date,b=b.getFullYear()+"-"+c.toTwoChar(b.getMonth())+"-"+c.toTwoChar(b.getDate())+" "+c.toTwoChar(b.getHours())+":"+c.toTwoChar(b.getMinutes())+":"+c.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);this.subject=encodeURIComponent(this.subject);
this.type=encodeURIComponent(this.type)};b.generateAlert=function(a){a=b.imageRequest(window.location.protocol+"//"+c.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+c.options.clientId+"&client="+c.options.client+"&publishPath="+c.options.publishPath+"&rid="+b.currentRuleId+"&did="+b.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};b.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};b.insertScript=function(a,d,e,h){var p=
document.getElementsByTagName("script"),g;h=void 0!==h?h:!0;if(void 0!==d?d:1)for(g=0;g<p.length;g++)if(p[g].src===a&&p[g].readyState&&/loaded|complete/.test(p[g].readyState))return;if(e){e=1==e&&"object"==typeof b.scDataObj?b.scDataObj:e;c.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));d=window.location.href;"object"===typeof e&&e.PageID&&(d=e.PageID,delete e.PageID);if("object"===typeof e)for(g in e){g=~d.indexOf("#")?d.slice(d.indexOf("#"),d.length):"";d=d.slice(0,g.length?d.length-g.length:
d.length);d+=~d.indexOf("?")?"&":"?";for(k in e)d+=k+"="+e[k]+"&";d=d.slice(0,-1)+g;break}a+="?";h&&(a+="r="+c.rand+"&");a+="ClientID="+encodeURIComponent(c.options.clientId)+"&PageID="+encodeURIComponent(d)}(function(a,b,d){var e=b.head||b.getElementsByTagName("head");setTimeout(function(){if("item"in e){if(!e[0]){setTimeout(arguments.callee,25);return}e=e[0]}var a=b.createElement("script");a.src=d;a.onload=a.onerror=function(){this.addEventListener&&(this.readyState="loaded")};e.insertBefore(a,
e.firstChild)},0)})(window,document,a)};b.loadScriptCallback=function(a,b,e){var d=document.getElementsByTagName("script"),c;e=d[0];for(c=0;c<d.length;c++)if(d[c].src===a&&d[c].readyState&&/loaded|complete/.test(d[c].readyState))try{b()}catch(g){window[ensightenOptions.ns].reportException(g)}finally{return}d=document.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;d.onerror=function(){this.addEventListener&&(this.readyState="loaded")};d.onload=d.onreadystatechange=function(){if(!this.readyState||
"complete"===this.readyState||"loaded"===this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&(this.readyState="loaded");try{b.call(this)}catch(g){window[ensightenOptions.ns].reportException(g)}}};e.parentNode.insertBefore(d,e)};b.unobtrusiveAddEvent=function(a,b,e){try{var d=a[b]?a[b]:function(){};a[b]=function(){e.apply(this,arguments);return d.apply(this,arguments)}}catch(p){window[ensightenOptions.ns].reportException(p)}};b.anonymous=function(a,d){return function(){try{b.currentRuleId=
d?d:"anonymous",a()}catch(e){window[ensightenOptions.ns].reportException(e)}}};b.setCurrentRuleId=function(a){b.currentRuleId=a};b.setCurrentDeploymentId=function(a){b.currentDeploymentId=a};b.bindImmediate=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMParsed=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMParsed}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMLoaded=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMLoaded}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindPageSpecificCompletion=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.conditionalRules}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindOnGetServerComponent=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.readyForServerComponent}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDataDefinitionComplete=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.checkHasRun=function(a){if(0===a.length)return!0;for(var d,e=0;e<a.length;++e)if(d=b.getRule(parseInt(a[e],10)),!d||!d.executionData.hasRun)return!1;return!0};b.bindDependencyImmediate=function(a,d,e,h,f){var g=[];if(!c.checkForInvalidDependencies(d,h,e,f)){g.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMLoaded=function(a,d,e,h,f){var g=[];if(!c.checkForInvalidDependencies(d,h,e,f)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMLoaded});g.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMParsed=function(a,d,e,h,f){var g=[];if(!c.checkForInvalidDependencies(d,
h,e,f)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMParsed});g.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,d,e,h,f){var g=[];if(!c.checkForInvalidDependencies(d,h,e,f)){g.push(function(){return window[ensightenOptions.ns].executionState.conditionalRules});
g.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyOnGetServerComponent=function(a,d,e,h,f){var g=[];if(!c.checkForInvalidDependencies(d,h,e,f)){g.push(function(){return window[ensightenOptions.ns].executionState.readyForServerComponent});g.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===
typeof a)a=new b.Rule({id:d||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,d,e,f,p){var g=[];if(!c.checkForInvalidDependencies(d,f,e,p)){g.push(function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete});g.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:f||-1,dependencies:g,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.dataDefintionIds=[];b.dataDefinitions=[];b.pageSpecificDataDefinitionsSet=!1;b.setPageSpecificDataDefinitionIds=function(a){for(var d=a.length,e=0;e<d;e++){var c=a[e];if(Array.prototype.indexOf)-1==b.dataDefinitionIds.indexOf(c)&&b.dataDefinitionIds.push(c);else{for(var f=!1,g=b.dataDefinitionIds.length,l=0;l<g;l++)if(b.dataDefinitionIds[l]===c){f=!0;break}f||b.dataDefinitionIds.push(c)}}b.pageSpecificDataDefinitionsSet=!0;n()};b.DataDefinition=function(a,b){this.id=
a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};b.registerDataDefinition=function(a,d){var e=b.dataDefinitions[d];e||(e=new b.DataDefinition(d,a),b.dataDefinitions[d]=e);e.startRegistrationTime||(e.startRegistration(),e.registrationFn(),e.endRegistration());b.pageSpecificDataDefinitionsSet&&n()};b.callOnDataDefintionComplete=function(){b.executionState.dataDefinitionComplete=
!0;b.testAll()};b.callOnDOMParsed=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};b.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=!0;window[ensightenOptions.ns].testAll()};b.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,e=a.length;b<e;b++)if(a[b].src&&a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&
"loaded"!=a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};b.callOnGetServerComponent=function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};b.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};b.hasDOMLoaded=
function(){return window[ensightenOptions.ns].executionState.DOMLoaded};b.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};var r=function(){var a=[],b=!1,e=!1;return{add:function(d){b&&!e?d():"function"==typeof d&&(a[a.length]=d)},exec:function(){e=!0;do{var d=a;a=[];b=!0;for(var c=0;c<d.length;c++)try{d[c].call(window)}catch(g){window[ensightenOptions.ns].reportException(g)}}while(0<a.length);e=!1},haveRun:function(){return b}}};b.new_fArray=
function(){return r()};c.timer=null;(function(){function a(a,b){return function(){a.apply(b,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var c=log4javascript.getDefaultLogger();b.log=a(c.info,c);b.debug=a(c.debug,c);b.info=a(c.info,c);b.warn=a(c.warn,c);b.error=a(c.error,c)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?
c.timer=window.setInterval(function(){/loaded|interactive|complete/.test(document.readyState)&&(clearInterval(c.timer),b.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",b.callOnDOMParsed,!1),window.addEventListener("load",b.callOnDOMLoaded,!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(d){setTimeout(arguments.callee,15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",
function(){window[ensightenOptions.ns].callOnDOMLoaded()}));document.readyState&&"complete"===document.readyState&&(b.executionState.DOMParsed=!0,b.executionState.DOMLoaded=!0);"true"===c.options.enableTagAuditBeacon&&b.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],d,e,h,l,g=0;g<c.ruleList.length;++g)e=c.ruleList[g],h=e.executionData.hasRun?"1":"0",l=e.deploymentId.toString()+"|"+e.id.toString()+"|"+h,a.push(l);
d="["+a.join(";")+"]";var m=window.location.protocol+"//"+c.nexus+"/"+encodeURIComponent(f.client)+"/"+encodeURIComponent(f.publishPath)+"/TagAuditBeacon.rnc?cid="+encodeURIComponent(f.clientId)+"&data="+d+"&idx=0&r="+c.rand;b.imageRequest(m)}catch(q){b.currentRuleId=-1,b.currentDeploymentId=-1,a=new c.BeaconException(q),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(b.testAll,c.options.interval);return b}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var f=window.performance;if(f){var f=f.timing||{},l=f.navigationStart||0,m={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",fetchStart:"fs",
loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"};var n="&ns="+encodeURIComponent(f.navigationStart);for(var c in m)if(void 0!==f[c]){var b=f[c]-l;n+="&"+m[c]+"="+(0<b?encodeURIComponent(b):0)}else n+="&"+m[c]+"=-1";window[ensightenOptions.ns].timing=n;c=ensightenOptions.nexus||"nexus.ensighten.com";f=ensightenOptions.staticJavascriptPath||
"";n=f.indexOf(".com/");l=f.indexOf("/code/");f=f.substring(n+4,l)+"/perf.rnc";f+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+c+f)}}});
	
if (!window[ensightenOptions.ns].data) {
/*
 MIT License (c) copyright 2011-2013 original author or authors  MIT License (c) copyright 2013 original author or authors */
window[ensightenOptions.ns].data||(window.JSON&&"object"===typeof JSON||(window[ensightenOptions.ns].JSON={}),function(){function e(a){return 10>a?"0"+a:a}function p(a){f.lastIndex=0;return f.test(a)?'"'+a.replace(f,function(a){var b=c[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function l(c,d){var e,h=k,m=d[c];m&&"object"===typeof m&&"function"===typeof m.toJSON&&(m=m.toJSON(c));"function"===typeof b&&(m=b.call(d,c,m));switch(typeof m){case "string":return p(m);
case "number":return isFinite(m)?String(m):"null";case "boolean":case "null":return String(m);case "object":if(!m)return"null";k+=a;var f=[];if("[object Array]"===Object.prototype.toString.apply(m)){var n=m.length;for(e=0;e<n;e+=1)f[e]=l(e,m)||"null";var q=0===f.length?"[]":k?"[\n"+k+f.join(",\n"+k)+"\n"+h+"]":"["+f.join(",")+"]";k=h;return q}if(b&&"object"===typeof b)for(n=b.length,e=0;e<n;e+=1){if("string"===typeof b[e]){var g=b[e];(q=l(g,m))&&f.push(p(g)+(k?": ":":")+q)}}else for(g in m)Object.prototype.hasOwnProperty.call(m,
g)&&(q=l(g,m))&&f.push(p(g)+(k?": ":":")+q);q=0===f.length?"{}":k?"{\n"+k+f.join(",\n"+k)+"\n"+h+"}":"{"+f.join(",")+"}";k=h;return q}}var g=window.JSON?window.JSON:window[ensightenOptions.ns].JSON;"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+e(this.getUTCMonth()+1)+"-"+e(this.getUTCDate())+"T"+e(this.getUTCHours())+":"+e(this.getUTCMinutes())+":"+e(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=
Boolean.prototype.toJSON=function(){return this.valueOf()});var d=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,f=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,k,a,c={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},b;"function"!==typeof g.stringify&&(g.stringify=function(c,d,e){var h;a=k="";if("number"===typeof e)for(h=0;h<e;h+=1)a+=
" ";else"string"===typeof e&&(a=e);if((b=d)&&"function"!==typeof d&&("object"!==typeof d||"number"!==typeof d.length))throw Error("JSON.stringify");return l("",{"":c})});"function"!==typeof g.parse&&(g.parse=function(a,b){function c(a,d){var h,e=a[d];if(e&&"object"===typeof e)for(h in e)if(Object.prototype.hasOwnProperty.call(e,h)){var m=c(e,h);void 0!==m?e[h]=m:delete e[h]}return b.call(a,d,e)}a=String(a);d.lastIndex=0;d.test(a)&&(a=a.replace(d,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));
if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){var h=eval("("+a+")");return"function"===typeof b?c({"":h},""):h}throw new SyntaxError("JSON.parse");})}(),window[ensightenOptions.ns].when=function(){function e(a,b,c,d){return l(a).then(b,c,d)}function p(a){this.then=a}function l(a){return g(function(b){b(a)})}function g(b){function e(a){n&&(f=d(a),c(n,f),
n=t)}function h(a){e(k(a))}function m(b){n&&c(n,a(b))}var f,n=[];try{b(e,h,m)}catch(E){h(E)}return new p(function(a,b,c){return g(function(d,e,h){n?n.push(function(m){m.then(a,b,c).then(d,e,h)}):r(function(){f.then(a,b,c).then(d,e,h)})})})}function d(a){return a instanceof p?a:a!==Object(a)?f(a):g(function(b,c,d){r(function(){try{var e=a.then;"function"===typeof e?z(e,a,b,c,d):b(f(a))}catch(y){c(y)}})})}function f(a){var b=new p(function(c){try{return"function"==typeof c?d(c(a)):b}catch(D){return k(D)}});
return b}function k(a){var b=new p(function(c,e){try{return"function"==typeof e?d(e(a)):b}catch(F){return k(F)}});return b}function a(b){var c=new p(function(d,e,h){try{return"function"==typeof h?a(h(b)):c}catch(y){return a(y)}});return c}function c(a,b){r(function(){for(var c,d=0;c=a[d++];)c(b)})}function b(a,b,c,d,h){m(2,arguments);return e(a,function(a){return g(function(c,d,h){function m(a){v(a)}function f(a){l(a)}var n;var g=a.length>>>0;var q=Math.max(0,Math.min(b,g));var k=[];var r=g-q+1;var x=
[];if(q){var v=function(a){x.push(a);--r||(l=v=u,d(x))};var l=function(a){k.push(a);--q||(l=v=u,c(k))};for(n=0;n<g;++n)n in a&&e(a[n],f,m,h)}else c(k)}).then(c,d,h)})}function q(a,b,c,d){m(1,arguments);return n(a,x).then(b,c,d)}function n(a,b){return e(a,function(a){return g(function(c,d,h){var m,f;var n=m=a.length>>>0;var g=[];if(n){var q=function(a,m){e(a,b).then(function(a){g[m]=a;--n||c(g)},d,h)};for(f=0;f<m;f++)f in a?q(a[f],f):--n}else c(g)})})}function r(a){1===v.push(a)&&A(h)}function h(){for(var a,
b=0;a=v[b++];)a();v=[]}function m(a,b){for(var c,d=b.length;d>a;)if(c=b[--d],null!=c&&"function"!=typeof c)throw Error("arg "+d+" must be a function");}function u(){}function x(a){return a}e.defer=function(){var a,b;var c={promise:t,resolve:t,reject:t,notify:t,resolver:{resolve:t,reject:t,notify:t}};c.promise=a=g(function(d,h,e){c.resolve=c.resolver.resolve=function(c){if(b)return l(c);b=!0;d(c);return a};c.reject=c.resolver.reject=function(c){if(b)return l(k(c));b=!0;h(c);return a};c.notify=c.resolver.notify=
function(a){e(a);return a}});return c};e.resolve=l;e.reject=function(a){return e(a,k)};e.join=function(){return n(arguments,x)};e.all=q;e.map=n;e.reduce=function(a,b){var c=z(B,arguments,1);return e(a,function(a){var d=a.length;c[0]=function(a,c,h){return e(a,function(a){return e(c,function(c){return b(a,c,h,d)})})};return G.apply(a,c)})};e.any=function(a,c,d,h){return b(a,1,function(a){return c?c(a[0]):a[0]},d,h)};e.some=b;e.isPromise=function(a){return a&&"function"===typeof a.then};p.prototype=
{otherwise:function(a){return this.then(t,a)},ensure:function(a){function b(){return l(a())}return this.then(b,b).yield(this)},yield:function(a){return this.then(function(){return a})},spread:function(a){return this.then(function(b){return q(b,function(b){return a.apply(t,b)})})},always:function(a,b){return this.then(a,a,b)}};var t;var v=[];var H=setTimeout;var A="function"===typeof setImmediate?"undefined"===typeof window?setImmediate:setImmediate.bind(window):"object"===typeof process&&process.nextTick?
process.nextTick:function(a){H(a,0)};var w=Function.prototype;var C=w.call;var z=w.bind?C.bind(C):function(a,b){return a.apply(b,B.call(arguments,2))};w=[];var B=w.slice;var G=w.reduce||function(a){var b=0;var c=Object(this);var d=c.length>>>0;var h=arguments;if(1>=h.length)for(;;){if(b in c){h=c[b++];break}if(++b>=d)throw new TypeError;}else h=h[1];for(;b<d;++b)b in c&&(h=a(h,c[b],b,c));return h};return e}(),function(){function e(d,e){return l.all(e||[],function(e){return d.apply(null,e)})}function p(d){var f=
g.call(arguments,1);return function(){return e(d,f.concat(g.call(arguments)))}}var l=window[ensightenOptions.ns].when;var g=[].slice;l.apply=e;l.call=function(d){return e(d,g.call(arguments,1))};l.lift=p;l.bind=p;l.compose=function(d){var f=g.call(arguments,1);return function(){var k=g.call(arguments),k=e(d,k);return l.reduce(f,function(a,c){return c(a)},k)}}}(),window[ensightenOptions.ns].data=function(e,p){function l(a,c){this.name="DataDefinitionException";this.message=c||"Data definitions cannot be resolved as there are invalid id(s): "+
a}var g,d={engines:{memory:{get:function(a){if(f.utils.isArray(a)){for(var c=[],b=0;b<a.length;b++)c.push(d.data[a[b]]);return e[ensightenOptions.ns].when.resolve(c)}c=d.dataDefinitions[a]||{storage:{get:function(){}}};c=c.storage.get(c);d.data[a]=c;return e[ensightenOptions.ns].when.resolve(d.data[a])},set:function(a,c){if(f.utils.isArray(a))for(var b in a)d.data[a[b]]=c[b];else d.data[a]=c;return e[ensightenOptions.ns].when.resolve(!0)},remove:function(a){if(f.utils.isArray(a))for(var c in a)delete d.data[a[c]];
else delete d.data[a];return e[ensightenOptions.ns].when.resolve(!0)},clear:function(a){d.data={};d.definitions={};return e[ensightenOptions.ns].when.resolve(!0)},all:function(){return e[ensightenOptions.ns].when.resolve(d.data)}}},normalizeInputArgs:function(a,c){var b={key:[],val:p},d;if(f.utils.isPlainObject(a))for(d in b.val=[],a)b.key.push(d),b.val.push(a[d]);else f.utils.isArray(a),b.key=a,b.val=c;return b},definitions:{},data:{}},f={utils:{isPlainObject:function(a){return!!a&&"[object Object]"===
Object.prototype.toString.call(a)},isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},escapeRegEx:function(a){try{return a.replace(/([.*+?^${}()|\[\]\/\\])/g,"\\$1")}catch(c){return a}}}},k=function(){return e[ensightenOptions.ns].when.reject("Not Implemented.")};l.prototype=Error();l.prototype||(l.prototype={});l.prototype.constructor=l;d.DataDefinitionException=l;d.checkForInvalidDataDefinitions=function(a){f.utils.isArray(a)||(a=[a]);return a&&0<a.length&&(a=a.join(","),
-1<a.indexOf("invalid_id"))?(e[ensightenOptions.ns].reportException(new d.DataDefinitionException(a)),!0):!1};d.collectAvailableDataDefinitions=function(a){for(var c=[],b=0;b<a.length;b++){var g=parseInt(a[b],10),n=e[ensightenOptions.ns].dataDefinitions[g];if(null===n||n===p)if(n=f.storage.session.get({id:g}),null!==n&&n!==p)f.set(g,n),d.dataDefinitions[g]={id:g,load:"visitor",storage:f.storage.visitor,missingDDFromCache:!0},c.push(e[ensightenOptions.ns].data.get(""+g));else return e[ensightenOptions.ns].reportException(new d.DataDefinitionException(a,
"Invalid data definition used: "+g)),{promises:[],isInvalid:!0};else c.push(e[ensightenOptions.ns].data.get(a[b]))}return{promises:c,isInvalid:!1}};d.getSync=function(a){function c(a){var c=a.extract||g,d=a.transform||n,h=!1,e=null,m=null;try{e=c()}catch(w){e=null,h=!0}try{m=d(e)}catch(w){m=null,h=!0}h&&b.push(a.id);return m}var b=[],g=function(){return document},n=function(a){return null!==a&&a!==p?a.toString():null},k=parseInt(a);a="string"===typeof a?a.split("."):[];var h={},m="";if(!isNaN(k)&&
"undefined"===typeof d.dataDefinitions[k])return e[ensightenOptions.ns].reportException(new d.DataDefinitionException(k,"Error resolving data definition: "+k+".  Does not exist on the page.")),"Data definition specified does not exist on the page";if(isNaN(k)&&"undefined"===typeof d.dataDefinitionsBySourceCollName[""+a[0]+"."+a[1]+"."+a[2]])return e[ensightenOptions.ns].reportException(new d.DataDefinitionException(a,"Error resolving data definition: "+a[0]+"."+a[1]+"."+a[2]+".  Does not exist on the page.")),
"Data definition specified does not exist on the page";isNaN(k)?3==a.length&&(h=f.getDataDefinitionBySourceCollectionName(a[0],a[1],a[2])):h=f.getDataDefinitionById(k);m=h.load&&h.load.match(/(session|visitor)/i)&&h.storage&&h.storage.get?h.storage.get(h):c(h);0<b.length&&e[ensightenOptions.ns].reportException(new d.DataDefinitionException(b,"Error resolving data definitions synchronously: "+b));return m};d.dataDefinitions={};d.dataDefinitionsBySourceCollName={};f.defineEngine=function(a,c){var b,
f=["get","set","remove","clear","all"];d.engines[a]=c;if(!c.returnsPromise)for(b=0;b<f.length;b++){var n=f[b];c[n]=e[ensightenOptions.ns].when.lift(c[n])}};f.storage={instance:{set:function(a,c){},get:function(a){return d.getSync(a.id)}},page:{set:function(a,c){},get:function(a){return d.data[a.id]}},session:{set:function(a,c){var b=f.storage.session.get({id:a}),d=new Date,n=d.getTime();d.setTime(n+18E5);null!=b&&(c=b);e[ensightenOptions.ns].data.cookie.utils.set(a,c,{expires:d.toGMTString()});b=
{expires:d.getTime(),value:c};e[ensightenOptions.ns].data.local.utils.set(a,b)},get:function(a){var c=e[ensightenOptions.ns].data.cookie.utils.get(a.id),b=e.JSON&&e.JSON.stringify?e.JSON:e[ensightenOptions.ns].JSON,b=b||{},d=new Date,d=d.getTime();if(null===c){try{var f=b.parse(e[ensightenOptions.ns].data.local.utils.get(a.id))}catch(r){f=null}null!=f&&(f.expires=+f.expires,d<=f.expires?c=f.value:""==f.expires&&f.value!=p?c=f.value:e[ensightenOptions.ns].data.local.utils.remove(a.id))}return c}},
visitor:{set:function(a,c){var b=f.storage.session.get({id:a});null!=b&&(c=b);e[ensightenOptions.ns].data.cookie.utils.set(a,c);e[ensightenOptions.ns].data.local.utils.set(a,{expires:"",value:c})},get:function(a){return f.storage.session.get(a)}}};f.getEngine=f.engine=function(a){return a?d.engines[a]||{get:k,set:k,remove:k,clear:k,all:k}:d.engines};f.all=function(a){return e[ensightenOptions.ns].data.engine(a||"memory").all()};f.get=function(a,c,b){c=c||"memory";b=b||{};-1<a.indexOf(",")&&(a=a.split(","));
a=d.normalizeInputArgs(a);return b.wait?d.getWait(a.key,e[ensightenOptions.ns].data.engine(c),b):d.data&&d.data.hasOwnProperty(a.key)?e[ensightenOptions.ns].data.engine(c).get(a.key):d.getWaitForKey(a.key,e[ensightenOptions.ns].data.engine(c),b)};d.getWait=function(a,c,b){var d=+new Date,g=e[ensightenOptions.ns].when.defer(),k=function(){var d=c.get(a);if(-1===b.wait)return d;d.then(function(a){b.setCheck(a)?g.resolve(a):setTimeout(h,b.interval)},function(a){setTimeout(h,b.interval)})},h=function(){var a=
+new Date-d;-1!==b.wait&&a<b.wait?k():g.reject("Timeout")};b.interval=b.interval||500;b.wait=b.wait||5E3;f.utils.isArray(a)?b.setCheck=b.setCheck||function(a){for(var b=!0,c=0;c<a.length;c++)b=b&&!!a[c];return b}:b.setCheck=b.setCheck||function(a){return!!a};k();return g.promise};d.getWaitForKey=function(a,c,b){var f=e[ensightenOptions.ns].when.defer(),g=function(){if(d.data&&d.data.hasOwnProperty(a)){var h=c.get(a);if(-1===b.wait)return h;h.then(function(a){f.resolve(a)},function(a){f.reject(a)})}else setTimeout(k,
b.interval)},k=function(){g()};b.interval=b.interval||100;b.wait=b.wait||1;g();return f.promise};f.set=function(a,c,b){var f=d.normalizeInputArgs(a,c);Array.prototype.slice.call(arguments);return e[ensightenOptions.ns].data.engine(b||"memory").set(f.key,f.val)};f.remove=function(a,c){return e[ensightenOptions.ns].data.engine(c||"memory").remove(a)};f.clear=function(a){return e[ensightenOptions.ns].data.engine(a||"memory").clear()};f.define=function(a,c){c&&(a.name=c.id||c.name);if(!a.name)return e[ensightenOptions.ns].when.reject(Error("Invalid parameters: missing 'name'"));
a.id=a.name;var b=a.load||"page";a.load=a.load||"javascript";a.load=-1<a.load.indexOf("javascript")?a.load:a.load+",javascript";a.trigger=a.trigger||function(){return e[ensightenOptions.ns].when.resolve()};a.priv=a.priv||!1;a.collection=a.collection||"Data Layer";a.persist=e[ensightenOptions.ns].data.engine("memory");a.storage=f.storage[b.toLowerCase()]||f.storage.page;var g=a.extract||function(){return document},k=a.transform||function(a){return a},r=function(b,c){var d=[];d.push(a.persist.set(b,
c));a.storage.set(a.id,c);"object"==typeof e[ensightenOptions.ns].data.dataExport&&e[ensightenOptions.ns].data.dataExport(b,c,a.collection);e[ensightenOptions.ns].when.all(d).then(function(a){h.resolve(a)},function(a){h.reject(a)})},h=e[ensightenOptions.ns].when.defer();try{var m=a.trigger()}catch(u){e[ensightenOptions.ns].reportException(new d.DataDefinitionException(null,'"'+u+'" error caught in Data Definition trigger: '+a.dataDefName+", ID:"+a.id+". Using bottom of body trigger.")),m=e[ensightenOptions.ns].data.bottomOfBodyTrigger()}m.then(function(){h.resolve(e[ensightenOptions.ns].when.reduce([function(){try{return g()}catch(u){return e[ensightenOptions.ns].reportException(new d.DataDefinitionException(null,
'"'+u+'" error caught in Data Definition extractor: '+a.dataDefName+", ID:"+a.id+".")),null}}(),function(){try{return k.apply(this,arguments)}catch(u){return e[ensightenOptions.ns].reportException(new d.DataDefinitionException(null,'"'+u+'" error caught in Data Definition transformer: '+a.dataDefName+", ID "+a.id+".")),null}},r],function(b,c,d,h){if(1==d)return c(b);2==d&&c(a.name,b)}))},function(a){h.reject(a)});d.dataDefinitions[a.id]=a;d.dataDefinitionsBySourceCollName[""+a.source+"."+a.collection+
"."+a.dataDefName]=a;return h.promise};f.checkConditions=function(a){var c,b={lt:function(a,b){var c=+a,f=+b;return isNaN(c)||isNaN(f)?(e[ensightenOptions.ns].reportException(new d.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+a+", compareTo: "+b)),!1):c<f},gt:function(a,b){var c=+a,f=+b;return isNaN(c)||isNaN(f)?(e[ensightenOptions.ns].reportException(new d.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+a+", compareTo: "+
b)),!1):c>f},eql:function(a,b){return a==b},exists:function(a,b){return null==a||a==p||""==a?!1:!0},re:function(a,b,c){b=new RegExp(b,c?"i":"");try{return a.match(b)}catch(m){return!1}},starts:function(a,c,d){c=f.utils.escapeRegEx(c);return b.re(a,"^"+c,d)},ends:function(a,c,d){c=f.utils.escapeRegEx(c);return b.re(a,c+"$",d)},contains:function(a,c,d){c=f.utils.escapeRegEx(c);return b.re(a,".*"+c+".*",d)}};b.is=b.eql;b["starts with"]=b.starts;b["ends with"]=b.ends;b["is greater than"]=b.gt;b["is less than"]=
b.lt;b.matches=b.re;for(c=0;c<a.values.length;c++){var g=(a.customComparator?a.customComparator[c]?a.customComparator[c]:b[a.comparators[c]]:b[a.comparators[c]])(a.values[c],a.compareTo[c],a.caseInsensitive?a.caseInsensitive[c]||!1:!1);a.not[c]&&(g=!g);if(!g)return!1}return!0};f.triggerPromise=function(a,c,b){b=b||5E3;var d=+new Date,f=e[ensightenOptions.ns].when.defer();(function(){var e=a();e!=c?f.resolve(e):+new Date-d<b?setTimeout(arguments.callee,200):f.reject("timed out")})();return f.promise};
f.timeoutPromise=function(a,c){var b=e[ensightenOptions.ns].when.defer();c=c||800;a.then(b.resolve,b.reject);setTimeout(function(){b.reject(Error("timed out"))},c);return b.promise};f.delayTrigger=function(a){a=a||10;var c=e[ensightenOptions.ns].when.defer();setTimeout(function(){c.resolve()},a);return c.promise};f.delayUntilTrigger=function(a,c,b,d){b=b||null;d=d||200;var f=+new Date,g=e[ensightenOptions.ns].when.defer();(function(){var e=a();e!=c?g.resolve(e):b?+new Date-f<b?setTimeout(arguments.callee,
d):g.reject("timed out"):setTimeout(arguments.callee,d)})();return g.promise};d.applyTrigger=function(a){var c=e[ensightenOptions.ns].when.defer();a(function(){c.resolve(!0)});return c.promise};f.immediateTrigger=function(){return d.applyTrigger(e[ensightenOptions.ns].bindImmediate)};f.bottomOfBodyTrigger=function(){return d.applyTrigger(e[ensightenOptions.ns].bindDOMParsed)};f.whenValueExistsTrigger=function(){return e[ensightenOptions.ns].when.resolve(this.extract())};f.afterEnsightenCompleteTrigger=
function(){return d.applyTrigger(e[ensightenOptions.ns].bindPageSpecificCompletion)};f.afterElementsDownloadedTrigger=function(){return d.applyTrigger(e[ensightenOptions.ns].bindDOMLoaded)};f.getAllDataDefinitionsOnCurrentPage=function(){return d.dataDefinitions};f.getAllDataDefinitionsOnCurrentPage_S_C_N=function(){return d.dataDefinitionsBySourceCollName};f.getDataDefinitionById=function(a){return d.dataDefinitions[a||-1]||{}};f.getDataDefinitionBySourceCollectionName=function(a,c,b){return d.dataDefinitionsBySourceCollName[""+
a+"."+c+"."+b]||{}};f.getDataDefinitionByPercentSyntax=function(a){a=(""+a).split("_");return 1>a.length?{}:d.dataDefinitions[a[1]]||{}};f.resolve=function(a,c){var b=this;var g=null;if(!d.checkForInvalidDataDefinitions(a))if(c)e[ensightenOptions.ns].bindDataDefinitionComplete(function(){var h=d.collectAvailableDataDefinitions(a);h.isInvalid||e[ensightenOptions.ns].when.all(h.promises).then(function(h){try{c.apply(b,h)}catch(u){e[ensightenOptions.ns].reportException(new d.DataDefinitionException(a,
"Error resolving data definitions: "+a+". Details: "+u))}},function(b){e[ensightenOptions.ns].reportException(new d.DataDefinitionException(a,"Error resolving data definitions: "+a+". Details: "+b))})});else{var k=[];g=a;f.utils.isArray(a)||(g=[a]);for(var l=0;l<g.length;l++)k.push(d.getSync(g[l]));return g=f.utils.isArray(a)?k:k[0]}};f.extract=function(a,c){var b="",d=function(a,b){var c=~b.indexOf("#")?b.split("#")[1]:"",d=c?0:~b.indexOf("[")?parseInt(b.match(/\[(\d+)\]/)[1]):0,e=(c?b.split("#")[0]:
d?b.split("[")[0]:b).toLowerCase();if(a==document&&"html"==e&&0==d)return document.getElementsByTagName("html")[0];if(~b.indexOf("#"))return document.getElementById(b.split("#")[1]);var h=a.firstChild;if(!h)return null;for(var f=0,d=0!=d?d-1:d;h;){if(1==h.nodeType){if(h.tagName.toLowerCase()==e&&""!=c&&h.id==c||h.tagName.toLowerCase()==e&&f==d&&""==c)return h;h.tagName.toLowerCase()==e&&f++}h=h.nextSibling}},f=function(a,b){a=a.split("/");for(var c=d(b||document,a[1]),e=2;e<a.length;e++){if(null==
c)return null;c=d(c,a[e])}return c},g=function(){for(var a={},b=e.document.getElementsByTagName("META")||[],c=0,d=b.length;c<d;c++){var h=b[c].name||b[c].getAttribute("property")||"";0!==h.length&&(a[h]=b[c].content)}return a}(),h=function(a){var b=g[a];if(b)return b;for(var b=e.document.getElementsByTagName("META")||[],c=0,d=b.length;c<d;c++){var h=b[c].name||b[c].getAttribute("property")||"";if(a==h)return b[c].content}},m=function(a){return(val=(new RegExp("&"+a+"=([^&]*)")).exec(e.location.search.replace(/^\?/,
"&")))?val[0].split("=")[1]:""},k=function(a){return(val=(new RegExp("^"+a+"=.*|;\\s*"+a+"=.*")).exec(e.document.cookie))?val[0].split("=")[1].split(";")[0]:""},l=function(a){(a=t(a))&&a.nodeType&&1==a.nodeType&&(a=a.value||a.innerHTML||"");return a.toString().replace(/\n|\r|\s\s+/g,"")||""},t=function(a){var b="";if(0==a.indexOf("/HTML/BODY"))b=f(a);else try{b=eval(a)}catch(A){b=""}return b};try{return c?"meta"==c?b=h(a):"cookie"==c?b=k(a):"param"==c?b=m(a):"content"==c?b=l(a):"event"==c?b=t(a):
"var"==c&&(b=e[a]):b=h(a)||k(a)||m(a)||l(a)||t(a)||e[a]||"",b||""}catch(v){return""}};"undefined"==typeof g&&(g={exports:{}});return f}(window),window[ensightenOptions.ns].data.defineEngine("store",function(){function e(a){return function(){var c=Array.prototype.slice.call(arguments,0);c.unshift(b);n.appendChild(b);b.addBehavior("#default#userData");b.load(k);c=a.apply(store,c);n.removeChild(b);return c}}function p(a){return a.replace(l,"___")}var l=RegExp("[!\"#$%&'()*+,/\\\\:;<=>?@[\\]^`{|}~]",
"g"),g={},d=window,f=d.document,k="localStorage",a,c=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};g.set=function(a,b){};g.get=function(a){};g.remove=function(a){};g.clear=function(){};try{if(k in d&&d[k]){var b=d[k];g.set=function(a,d){var e,h=window.JSON&&window.JSON.stringify?window.JSON:window[ensightenOptions.ns].JSON;if(c(a)){var f=0;for(e=a.length;f<e;f++)b.setItem(a[f],"string"===typeof d[f]?d[f]:h.stringify(d[f]))}else b.setItem(a,"string"===typeof d?
d:h.stringify(d))};g.get=function(a){if(c(a)){var d={},e;var f=0;for(e=a.length;f<e;f++)d[a[f]]=b.getItem(a[f]);return d}return b.getItem(a)};g.remove=function(a){if(c(a)){var d;var e=0;for(d=a.length;e<d;e++)b.removeItem(a[e])}else b.removeItem(a)};g.clear=function(){b.clear()};g.all=function(){return b}}else if("globalStorage"in d&&d.globalStorage)b=d.globalStorage[d.location.hostname],g.set=function(a,d){if(c(a)){var e;var f=0;for(e=a.length;f<e;f++)b[a[f]]=d[f]}else b[a]=d},g.get=function(a){if(c(a)){var d=
{},e;var f=0;for(e=a.length;f<e;f++)d[a[f]]=b[a[f]]&&b[a[f]].value;return d}return b[a]&&b[a].value},g.remove=function(a){if(c(a)){var d;var e=0;for(d=a.length;e<d;e++)delete b[a[e]]}else delete b[a]},g.clear=function(){for(var a in b)delete b[a]},g.all=function(){return b};else if(f.documentElement.addBehavior){try{var q=new ActiveXObject("htmlfile");q.open();q.write('<script>document.w=window\x3c/script><iframe src="/favicon.ico"></frame>');q.close();var n=q.w.frames[0].document;b=n.createElement("div")}catch(h){b=
f.createElement("div"),n=f.body}g.set=e(function(a,b,d){if(c(b)){var e;var f=0;for(e=b.length;f<e;f++){fixedKey=p(b[f]);if(void 0===d[f])return g.remove(fixedKey);a.setAttribute(fixedKey,d[f]);a.save(k)}}else{fixedKey=p(b);if(void 0===d)return g.remove(fixedKey);a.setAttribute(fixedKey,d);a.save(k)}});g.get=e(function(a,b){if(c(b)){var d={},e;var f=0;for(e=b.length;f<e;f++){var h=p(b[f]);d[b[f]]=a.getAttribute(h)}return d}b=p(b);return a.getAttribute(b)});g.remove=e(function(a,b){if(c(b)){var d;var e=
0;for(d=b.length;e<d;e++)a.removeAttribute(p(b[e])),a.save(k)}else b=p(b),a.removeAttribute(b),a.save(k)});g.clear=e(function(a){var b=a.XMLDocument.documentElement.attributes;a.load(k);for(var c=0,d;d=b[c];c++)a.removeAttribute(d.name);a.save(k)});g.all=e(function(a){for(var b=a.XMLDocument.documentElement.attributes,c={},d=0,e;e=b[d];++d){var f=p(e.name);c[e.name]=a.getAttribute(f)}return c})}}catch(h){}var r={};for(a in g)r[a]=g[a];r.testStorage=function(){try{var a="tk_"+Math.ceil(5E7*Math.random());
r.set(a,"test");if("test"===r.get(a))return r.remove(a),!0}catch(m){}return!1};g.utils=r;return window[ensightenOptions.ns].data.local=g}()),window[ensightenOptions.ns].data.defineEngine("cookie",function(e,p){var l=function(){return l.get.apply(l,arguments)},g=l.utils={isArray:Array.isArray||function(d){return"[object Array]"===Object.prototype.toString.call(d)},isPlainObject:window[ensightenOptions.ns].data.utils.isPlainObject,toArray:function(d){return Array.prototype.slice.call(d)},getKeys:Object.keys||
function(d){var e=[],g="";for(g in d)d.hasOwnProperty(g)&&e.push(g);return e},escape:function(d){return String(d).replace(/[,;"\\=\s%]/g,function(d){return encodeURIComponent(d)})},retrieve:function(d,e){return null==d?e:d},getAllCookies:function(){if(""===e.cookie)return{};for(var d=e.cookie.split("; "),f={},g=0,a=d.length;g<a;g++){var c=d[g].split("=");f[decodeURIComponent(c[0])]=decodeURIComponent(c[1])}return f},set:function(d,f,k){k=k||-1;if(g.isPlainObject(d))for(var a in d)d.hasOwnProperty(a)&&
l.set(a,d[a],f);else if(g.isArray(d)){var c;a=0;for(c=d.length;a<c;a++)l.set(d[a],f[a],k)}else{a=k.expires!==p?k.expires:l.defaults.expires||"";"number"===typeof a&&(a=new Date(a));a=g.isPlainObject(a)&&"toGMTString"in a?";expires="+a.toGMTString():g.isPlainObject(a)&&a instanceof Date?";expires="+a.toUTCString():";expires="+a;c=(c=k.path||l.defaults.path)?";path="+c:"";var b=k.domain||l.defaults.domain,b=b?";domain="+b:"";k=k.secure||l.defaults.secure?";secure":"";e.cookie=g.escape(d)+"="+g.escape(f)+
a+c+b+k}},get:function(d,e){e=e||p;var f=g.getAllCookies();if(g.isArray(d)){var a={};for(var c=0,b=d.length;c<b;c++)a[d[c]]=g.retrieve(f[d[c]],e),a[d[c]]===p&&(a[d[c]]=null);return a}a=g.retrieve(f[d],e);return a===p?null:a},getGMTString:function(d){var e=new Date;e.setTime(e.getTime()+864E5*d);return e.toGMTString()}};l.defaults={path:"/",expires:g.getGMTString(90)};l.set=function(d,e){g.set(d,e)};l.remove=function(d){d=g.isArray(d)?d:g.toArray(arguments);for(var e=0,k=d.length;e<k;e++)g.set(d[e],
"",{expires:-1})};l.clear=function(){return l.remove(g.getKeys(g.getAllCookies()))};l.get=function(d,e){return g.get(d,e)};l.all=function(){return g.getAllCookies()};l.utils=g;return window[ensightenOptions.ns].data.cookie=l}(document)));
}
		
window[ensightenOptions.ns].ensEvent||(window[ensightenOptions.ns].ensEvent=function(n,u){var k={queue:{},pollQueue:{},pushTrigger:function(b,c){if("[object Array]"===Object.prototype.toString.call(b)){for(var g=0;g<b.length;g++)k.pushTrigger(b[g],c);return!0}if("string"!=typeof b)return!1;this.queue[b]=this.queue[b]||{fn:[]};"function"==typeof c&&this.queue[b].fn.push(c);return!0},callTrigger:function(b,c,g){if("string"!=typeof b)return!1;b=k.queue[b];if("object"==typeof b&&b.fn&&b.fn.length&&(0!=
b.fireOnFirstSet&&c==u||c!=u&&0!=b.fireOnUpdate))for(c=0;c<b.fn.length;c++)b.fn[c].call(this)},setPollOptions:function(b,c,g){this.queue[b]=this.queue[b]||{fn:[]};this.queue[b].fireOnFirstSet=c;this.queue[b].fireOnUpdate=g},callPoll:function(b,c,g,n,r){if("string"==typeof b&&c&&c.length&&!(1>c.length)){for(var p=0;p<c.length;p++)k.setPollOptions(c[p],n,r);k.pushWatch(b,c,g)}},pushWatch:function(b,c,g){this.pollQueue[b]||(this.pollQueue[b]={previousVal:u,eventArr:[],valueFn:g});this.pollQueue[b].eventArr=
this.pollQueue[b].eventArr.concat(c);this.pollQueue[b].valueFn=g},globalWatch:function(){setInterval(function(){for(var b in k.pollQueue){var c=k.pollQueue[b],g=c.valueFn(b);if(c.previousVal!==g&&null!==g&&""!==g){for(var p=0;p<c.eventArr.length;p++)k.callTrigger.call(n,c.eventArr[p],c.previousVal,g);k.pollQueue[b].previousVal=g}}},500)}};k.globalWatch();return{add:function(b,c){return k.pushTrigger(b,c)},get:function(b){return k.queue[b]},trigger:function(b,c){return k.callTrigger.call(c||n,b)},
poll:function(b,c,g,p,r){r=r||n[ensightenOptions.ns].data.resolve;return k.callPoll(b,c,r,g,p)}}}(window),function(n,u,k){u[n]=k()}("qwery",window[ensightenOptions.ns],function(){function n(){this.c={}}function u(a){return H.g(a)||H.s(a,"(^|\\s+)"+a+"(\\s+|$)",1)}function k(a,d){for(var e=0,f=a.length;e<f;e++)d(a[e])}function b(a){for(var d=[],e=0,f=a.length;e<f;++e)l(a[e])?d=d.concat(a[e]):d[d.length]=a[e];return d}function c(a){for(var d=0,e=a.length,f=[];d<e;d++)f[d]=a[d];return f}function g(a){for(;(a=
a.previousSibling)&&1!=a.nodeType;);return a}function p(a,d,e,f,b,h,l,c,g,k,y){var I,B,m;if(1!==this.nodeType||d&&"*"!==d&&this.tagName&&this.tagName.toLowerCase()!==d||e&&(I=e.match(Q))&&I[1]!==this.id)return!1;if(e&&(m=e.match(R)))for(a=m.length;a--;)if(!u(m[a].slice(1)).test(this.className))return!1;if(g&&v.pseudos[g]&&!v.pseudos[g](this,y))return!1;if(f&&!l)for(B in g=this.attributes,g)if(Object.prototype.hasOwnProperty.call(g,B)&&(g[B].name||B)==b)return this;return f&&!x(h,S(this,b)||"",l)?
!1:this}function r(a){return J.g(a)||J.s(a,a.replace(T,"\\$1"))}function x(a,d,e){switch(a){case "=":return d==e;case "^=":return d.match(w.g("^="+e)||w.s("^="+e,"^"+r(e),1));case "$=":return d.match(w.g("$="+e)||w.s("$="+e,r(e)+"$",1));case "*=":return d.match(w.g(e)||w.s(e,r(e),1));case "~=":return d.match(w.g("~="+e)||w.s("~="+e,"(?:^|\\s+)"+r(e)+"(?:\\s+|$)",1));case "|=":return d.match(w.g("|="+e)||w.s("|="+e,"^"+r(e)+"(-|$)",1))}return 0}function q(a,d){var e=[],f=[],b,h,l=d,c=C.g(a)||C.s(a,
a.split(K)),g=a.match(L);if(!c.length)return e;var m=(c=c.slice(0)).pop();c.length&&(b=c[c.length-1].match(M))&&(l=N(d,b[1]));if(!l)return e;var y=m.match(E);var v=l!==d&&9!==l.nodeType&&g&&/^[+~]$/.test(g[g.length-1])?function(a){for(;l=l.nextSibling;)1==l.nodeType&&(y[1]?y[1]==l.tagName.toLowerCase():1)&&(a[a.length]=l);return a}([]):l.getElementsByTagName(y[1]||"*");b=0;for(m=v.length;b<m;b++)if(h=p.apply(v[b],y))e[e.length]=h;if(!c.length)return e;k(e,function(a){t(a,c,g)&&(f[f.length]=a)});return f}
function t(a,d,e,b){function l(a,b,c){for(;c=U[e[b]](c,a);)if(f(c)&&p.apply(c,d[b].match(E)))if(b){if(h=l(c,b-1,c))return h}else return c}var h;return(h=l(a,d.length-1,a))&&(!b||z(h,b))}function f(a,d){return a&&"object"===typeof a&&(d=a.nodeType)&&(1==d||9==d)}function h(a){var d=[],e;var f=0;a:for(;f<a.length;++f){for(e=0;e<d.length;++e)if(d[e]==a[f])continue a;d[d.length]=a[f]}return d}function l(a){return"object"===typeof a&&isFinite(a.length)}function N(a,d,e){return 9===a.nodeType?a.getElementById(d):
a.ownerDocument&&((e=a.ownerDocument.getElementById(d))&&z(e,a)&&e||!z(a,a.ownerDocument)&&F('[id="'+d+'"]',a)[0])}function v(a,d){var e,h;var g=d?"string"==typeof d?v(d)[0]:!d.nodeType&&l(d)?d[0]:d:m;if(!g||!a)return[];if(a===window||f(a))return!d||a!==window&&f(g)&&z(a,g)?[a]:[];if(a&&l(a))return b(a);if(e=a.match(V)){if(e[1])return(h=N(g,e[1]))?[h]:[];if(e[2])return c(g.getElementsByTagName(e[2]));if(W&&e[3])return c(g.getElementsByClassName(e[3]))}return F(a,g)}function y(a,d){return function(e){var f,
b;O.test(e)?9!==a.nodeType&&((b=f=a.getAttribute("id"))||a.setAttribute("id",b="__qwerymeupscotty"),d(a.parentNode||a,'[id="'+b+'"]'+e,!0),f||a.removeAttribute("id")):e.length&&d(a,e,!1)}}var m=document,D=m.documentElement,F,Q=/#([\w\-]+)/,R=/\.[\w\-]+/g,M=/^#([\w\-]+)$/,X=/^([\w]+)?\.([\w\-]+)$/,O=/(^|,)\s*[>~+]/,Y=/^\s+|\s*([,\s\+\~>]|$)\s*/g,A=/[\s\>\+\~]/,P=/(?![\s\w\-\/\?\&\=\:\.\(\)\!,@#%<>\{\}\$\*\^'"]*\]|[\s\w\+\-]*\))/,T=/([.*+?\^=!:${}()|\[\]\/\\])/g,V=new RegExp(M.source+"|"+/^([\w\-]+)$/.source+
"|"+/^\.([\w\-]+)$/.source),L=new RegExp("("+A.source+")"+P.source,"g"),K=new RegExp(A.source+P.source),E=new RegExp(/^(\*|[a-z0-9]+)?(?:([\.\#]+[\w\-\.#]+)?)/.source+"("+/\[([\w\-]+)(?:([\|\^\$\*\~]?\=)['"]?([ \w\-\/\?\&\=\:\.\(\)\!,@#%<>\{\}\$\*\^]+)["']?)?\]/.source+")?("+/:([\w\-]+)(\(['"]?([^()]+)['"]?\))?/.source+")?"),U={" ":function(a){return a&&a!==D&&a.parentNode},">":function(a,d){return a&&a.parentNode==d.parentNode&&a.parentNode},"~":function(a){return a&&a.previousSibling},"+":function(a,
d,e,f){return a?(e=g(a))&&(f=g(d))&&e==f&&e:!1}};n.prototype={g:function(a){return this.c[a]||void 0},s:function(a,d,e){d=e?new RegExp(d):d;return this.c[a]=d}};var H=new n,J=new n,w=new n,C=new n,z="compareDocumentPosition"in D?function(a,d){return 16==(d.compareDocumentPosition(a)&16)}:"contains"in D?function(a,d){d=9===d.nodeType||d==window?D:d;return d!==a&&d.contains(a)}:function(a,d){for(;a=a.parentNode;)if(a===d)return 1;return 0},S=function(){var a=m.createElement("p");return(a.innerHTML=
'<a href="#x">x</a>',"#x"!=a.firstChild.getAttribute("href"))?function(a,e){return"class"===e?a.className:"href"===e||"src"===e?a.getAttribute(e,2):a.getAttribute(e)}:function(a,e){return a.getAttribute(e)}}(),W=!!m.getElementsByClassName,Z=m.querySelector&&m.querySelectorAll,aa=function(a,d){var e=[],f,b;try{if(9===d.nodeType||!O.test(a))return c(d.querySelectorAll(a));k(f=a.split(","),y(d,function(a,d){b=a.querySelectorAll(d);1==b.length?e[e.length]=b.item(0):b.length&&(e=e.concat(c(b)))}));return 1<
f.length&&1<e.length?h(e):e}catch(ba){}return G(a,d)},G=function(a,d){var e=[],f,b;a=a.replace(Y,"$1");if(f=a.match(X)){var l=u(f[2]);f=d.getElementsByTagName(f[1]||"*");var c=0;for(b=f.length;c<b;c++)l.test(f[c].className)&&(e[e.length]=f[c]);return e}k(f=a.split(","),y(d,function(a,f,h){l=q(f,a);c=0;for(b=l.length;c<b;c++)if(9===a.nodeType||h||z(l[c],d))e[e.length]=l[c]}));return 1<f.length&&1<e.length?h(e):e},A=function(a){"undefined"!==typeof a.useNativeQSA&&(F=a.useNativeQSA?Z?aa:G:G)};A({useNativeQSA:!0});
v.configure=A;v.uniq=h;v.is=function(a,d,e){if(f(d))return a==d;if(l(d))return!!~b(d).indexOf(a);for(var c=d.split(","),h;d=c.pop();)if(h=C.g(d)||C.s(d,d.split(K)),d=d.match(L),h=h.slice(0),p.apply(a,h.pop().match(E))&&(!h.length||t(a,h,d,e)))return!0;return!1};v.pseudos={};return v}),function(){function n(f,b,c){p||(p=window[ensightenOptions.ns].qwery);var h=p;if((h=h.call(c,b,c))&&0<h.length){if("_root"==b)f=c;else if(f===c)f=void 0;else{b:{for(var l=h.length,g=0;g<l;g++)if(f===h[g]){h=!0;break b}h=
!1}h||(f.parentNode?(r++,f=n(f.parentNode,b,c)):f=void 0)}return f}return!1}function u(f,b,c,g){q[f.id]||(q[f.id]={});q[f.id][b]||(q[f.id][b]={});q[f.id][b][c]||(q[f.id][b][c]=[]);q[f.id][b][c].push(g)}function k(f,b,c,g){if(g||c)if(g)for(var h=0;h<q[f.id][b][c].length;h++){if(q[f.id][b][c][h]===g){q[f.id][b][c].pop(h,1);break}}else delete q[f.id][b][c];else q[f.id][b]={}}function b(b,c,l){if(q[b][l]){var f=c.target||c.srcElement,h,k,m={},p=k=0;r=0;for(h in q[b][l])q[b][l].hasOwnProperty(h)&&(k=n(f,
h,t[b].element))&&g.matchesEvent(l,t[b].element,k,"_root"==h,c)&&(r++,q[b][l][h].match=k,m[r]=q[b][l][h]);c.stopPropagation=function(){c.cancelBubble=!0};for(k=0;k<=r;k++)if(m[k])for(p=0;p<m[k].length;p++){if(!1===m[k][p].call(m[k].match,c)){g.cancel(c);return}if(c.cancelBubble)return}}}function c(c,h,l,p){function f(c){return function(f){b(n,f,c)}}c instanceof Array||(c=[c]);l||"function"!=typeof h||(l=h,h="_root");var n=this.id,m;for(m=0;m<c.length;m++)q[n]&&q[n][c[m]]||g.addEvent(this,c[m],f(c[m])),
p?k(this,c[m],h,l):u(this,c[m],h,l);return this}function g(b,c,l,k){if("string"==typeof b&&"function"==typeof c||"string"==typeof c)g(document).on(b,c,l,k||!1);if(!(this instanceof g)){for(var f in t)if(t[f].element===b)return t[f];x++;t[x]=new g(b,x);t[x]._on=t[x].on;t[x].on=function(b,c,f,g){var h="function"==typeof c?c:f;if("function"==typeof c?f:g)b=[b],"string"==typeof c&&b.push(c),b.push(function(b){return function(c){c.defaultPrevented||window[ensightenOptions.ns].Delegate.load(this);if(this.nodeName&&
"a"!=this.nodeName.toLowerCase())return b.call(this);"undefined"!=typeof c.preventDefault?c.preventDefault():c.returnValue=!1;b.call(this)}}(h)),this._on.apply(this,b);else return this._on.call(this,b,c,f)};return t[x]}this.element=b;this.id=c}var p,r=0,x=0,q={},t={};g.prototype.on=function(b,g,l){return c.call(this,b,g,l)};g.prototype.off=function(b,g,l){return c.call(this,b,g,l,!0)};g.cancel=function(b){b.preventDefault();b.stopPropagation()};g.addEvent=function(b,c,g){b.element.addEventListener(c,
g,"blur"==c||"focus"==c)};g.matchesEvent=function(){return!0};g.load=function(b){setTimeout(function(b,c){return function(){if(b.nodeName&&"a"==b.nodeName.toLowerCase()){if(c&&/^javascript\s*\:/.test(c))return(new Function(unescape(c))).call(window);c&&(window.location.href=c)}}}(b,b.href||""),750)};window[ensightenOptions.ns].Delegate=g}(),function(n){var u=n.addEvent;n.addEvent=function(k,b,c){if(k.element.addEventListener)return u(k,b,c);"focus"==b&&(b="focusin");"blur"==b&&(b="focusout");k.element.attachEvent("on"+
b,c)};n.cancel=function(k){k.preventDefault&&k.preventDefault();k.stopPropagation&&k.stopPropagation();k.returnValue=!1;k.cancelBubble=!0}}(window[ensightenOptions.ns].Delegate),window[ensightenOptions.ns].on=window[ensightenOptions.ns].Delegate);
Bootstrapper.dataDefinitionIds = [47986,23419];Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){var blackList=["[^_]name","DisplayName","FIRSTNAME","LASTNAME","phone","displayName","CCNum","emailaddress","clientname","Email","email-address","nickname","accountnumber","accounttransit","acct_num","[^_]nick_name","cis_name","gw_name","gic_nick_name","RSP_ACCOUNT","CIS_ACCT","SIN",
"last-name"];var dL=document.location.href;for(var i=0;i<blackList.length;i++){var re=new RegExp("((\x26)?"+blackList[i]+"\x3d[^\x26#]*)");dL=dL.replace(re,"")}var newRe=new RegExp("\\?\x26");dL=dL.replace(newRe,"?");return dL},transform:function(val){return val?val:""},load:"page",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"DocumentLocation-BlackList",collection:"Page",source:"Manage",priv:"false"},{id:"47986"})},47986)},-1,-1);
Bootstrapper.bindImmediate(function(){var ddConditions={"not":[null],"caseInsensitive":["ignore case"],"compareTo":["/com.rbc._3m00.olb.web.portal.pg.myacct.accountsummary"],"requiredData":["23419"],"comparators":["is"]};Bootstrapper.data.resolve(ddConditions.requiredData,function(){ddConditions.values=Array.prototype.slice.call(arguments,0);var Bootstrapper=window["Bootstrapper"];if(Bootstrapper.data.checkConditions(ddConditions))Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];
var ensightenOptions=Bootstrapper.ensightenOptions;var i=window,r="ga";i.GoogleAnalyticsObject=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)};i[r].l=1*new Date;i[r](function(){setTimeout(function(){i[r]("set",{"dimension33":window.dataLayer.ageBrackets,"dimension34":window.dataLayer.products,"dimension35":window.dataLayer.gender,"dimension36":window.dataLayer.location,"dimension37":window.dataLayer.lifeStatus,"dimension38":window.dataLayer.occupation,"dimension39":window.dataLayer.isRBCEmployee,
"dimension51":window.dataLayer.ecsID})},1)})},2099743,[2093967],487064,[427472])})},-1,-1);
Bootstrapper.bindImmediate(function(){var ddConditions={"not":[null],"caseInsensitive":["ignore case"],"compareTo":["/com.rbc._3m00.olb.web.portal.pg.myacct.accountsummary"],"requiredData":["23419"],"comparators":["is"]};Bootstrapper.data.resolve(ddConditions.requiredData,function(){ddConditions.values=Array.prototype.slice.call(arguments,0);var Bootstrapper=window["Bootstrapper"];if(Bootstrapper.data.checkConditions(ddConditions))Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];
var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.isFunction=function(functionToCheck){var getType={};return functionToCheck&&getType.toString.call(functionToCheck)==="[object Function]"};Bootstrapper.bindDOMParsed(function(){var i=window,r="ga";i.GoogleAnalyticsObject=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)};i[r].l=1*new Date;window["ga"](function(){function hook(a,c,d,e){if(a=="#")Bootstrapper.bindDOMLoaded(d);else if(Bootstrapper.on)if("object"==typeof a)if(a.length)for(var b=
0;b<a.length;b++)Bootstrapper.on(a[b]).on(c,d);else Bootstrapper.on(a).on(c,d);else Bootstrapper.on(document).on(c,a,d,e);else if("string"!=typeof a||a.indexOf("#")?"string"!=typeof a||a.indexOf(".")||(a=document.getElementsByClassName(a.slice(1))):a=document.getElementById(a.slice(1)),"object"==typeof a)if(a.length)for(b=0;b<a.length;b++)Bootstrapper.unobtrusiveAddEvent(a[b],"on"+c,d);else Bootstrapper.unobtrusiveAddEvent(a,"on"+c,d)}var a=[['a[href*\x3d"_AlertCentre"]',"mousedown",{"hitType":"pageview",
"page":"/olb/entity-page/e-alerts-href-link"},true]];for(var i=0;i<a.length;i++){var element="";element=0==a[i][0].indexOf("#")?document.getElementById(a[i][0].slice(1)):0==a[i][0].indexOf(".")?document.getElementsByClassName(a[i][0].slice(1))[0]:a[i][0],hook(a[i][0],a[i][1],function(){var e=i;return function(){var helper=[['a[href*\x3d"_AlertCentre"]',"mousedown",{"hitType":"pageview","page":"/olb/entity-page/e-alerts-href-link"},true]];var i=helper[e][2],a="event";"pageview"==i.hitType&&(a=i.hitType);
for(var t in i)Bootstrapper.isFunction(i[t])&&(i[t]=i[t].call(this));window["ga"]("send",a,i)}}(),a[i][3])}})})},1610212,428699)})},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return typeof dataLayer!=="undefined"?typeof dataLayer.pageID!=="undefined"?dataLayer.pageID:"":""},load:"instance",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"PageID",collection:"dataLayer",source:"Manage",priv:"false"},{id:"23419"})},23419)},-1,-1);
Bootstrapper.bindImmediate(function(){var ddConditions={"not":[null],"caseInsensitive":["ignore case"],"compareTo":["/com.rbc._3m00.olb.web.portal.pg.myacct.banking.pa"],"requiredData":["23419"],"comparators":["is"]};Bootstrapper.data.resolve(ddConditions.requiredData,function(){ddConditions.values=Array.prototype.slice.call(arguments,0);var Bootstrapper=window["Bootstrapper"];if(Bootstrapper.data.checkConditions(ddConditions))Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];
var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.isFunction=function(functionToCheck){var getType={};return functionToCheck&&getType.toString.call(functionToCheck)==="[object Function]"};Bootstrapper.bindDOMParsed(function(){var i=window,r="ga";i.GoogleAnalyticsObject=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)};i[r].l=1*new Date;window["ga"](function(){function hook(a,c,d,e){if(a=="#")Bootstrapper.bindDOMLoaded(d);else if(Bootstrapper.on)if("object"==typeof a)if(a.length)for(var b=
0;b<a.length;b++)Bootstrapper.on(a[b]).on(c,d);else Bootstrapper.on(a).on(c,d);else Bootstrapper.on(document).on(c,a,d,e);else if("string"!=typeof a||a.indexOf("#")?"string"!=typeof a||a.indexOf(".")||(a=document.getElementsByClassName(a.slice(1))):a=document.getElementById(a.slice(1)),"object"==typeof a)if(a.length)for(b=0;b<a.length;b++)Bootstrapper.unobtrusiveAddEvent(a[b],"on"+c,d);else Bootstrapper.unobtrusiveAddEvent(a,"on"+c,d)}var a=[['a[href*\x3d"_AlertCentre"]',"mousedown",{"hitType":"pageview",
"page":"/olb/personal/accts-summary-page/e-alerts-href-link"},true]];for(var i=0;i<a.length;i++){var element="";element=0==a[i][0].indexOf("#")?document.getElementById(a[i][0].slice(1)):0==a[i][0].indexOf(".")?document.getElementsByClassName(a[i][0].slice(1))[0]:a[i][0],hook(a[i][0],a[i][1],function(){var e=i;return function(){var helper=[['a[href*\x3d"_AlertCentre"]',"mousedown",{"hitType":"pageview","page":"/olb/personal/accts-summary-page/e-alerts-href-link"},true]];var i=helper[e][2],a="event";
"pageview"==i.hitType&&(a=i.hitType);for(var t in i)Bootstrapper.isFunction(i[t])&&(i[t]=i[t].call(this));window["ga"]("send",a,i)}}(),a[i][3])}})})},1610218,428700)})},-1,-1);
Bootstrapper.bindImmediate(function(){var ddConditions={"not":[null],"caseInsensitive":[null],"compareTo":["/com.rbc._3m00.olb.web.portal.pg.myacct.banking.pa.gasdetails.viewdirectdepositform"],"requiredData":["23419"],"comparators":["is"]};Bootstrapper.data.resolve(ddConditions.requiredData,function(){ddConditions.values=Array.prototype.slice.call(arguments,0);var Bootstrapper=window["Bootstrapper"];if(Bootstrapper.data.checkConditions(ddConditions))Bootstrapper.bindImmediate(function(){var Bootstrapper=
window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;jQuery("#btn_submit").on("click",function(){(new Image).src="//rbc.bridgetrack.com/track/?id\x3d14895\x26r\x3d"+Math.random()})},1898613,463819)})},-1,-1);Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();